### ISSUE TITLE
Color Scheme/Plugin for editors implementing this idea

### ISSUE THREAD

**Issue by varemenos** [daniellmb/JavaScript-Scope-Context-Coloring#1]
Someone should try make a color scheme for editors (Sublime Text 2, Textmate, Coda, etc) with this idea.
It would be great to be able to switch to the JS-Scope color scheme to make sure everything you wrote is properly scoped.

[alternative solution](https://github.com/daniellmb/JavaScript-Scope-Context-Coloring/issues/1#issuecomment-16027158)

[Kinda relevant discussion & brainstorming](https://plus.google.com/u/0/113127438179392830442/posts/XjR4WmSDFAV)

**Comment by dansherpa** [comment]
+1 on that!

**Comment by mstdokumaci** [comment]
+1 for sublime :)

**Comment by adewinter** [comment]
+1 for Sublime!

**Comment by varemenos** [comment]
Alternative idea (and possibly a more realistic solution):

> I'm not sure how this can be implemented as a color scheme. I guess a better idea would be to make it a plugin and have a shortcut to toggle between color-scope and syntax highlighting.﻿

**Comment by mazurov** [comment]
For SublimeText: https://github.com/mazurov/sublime-levels

![levels_demo](https://f.cloud.github.com/assets/75759/372777/42933c8a-a36d-11e2-9465-d758a16b41c3.gif)

**Comment by adardesign** [comment]
This should be able to be toggled easily

**Comment by mazurov** [comment]
Ctrl+Shift+O - switch off the scope coloring mode. (Command "Levels: off). P.S. if you have an issue on SublimeText plugin - post your issue at the plugin repository.

**Comment by adardesign** [comment]
@mazurov  Awesome, Thanks!

**Comment by daniellmb** [comment]
I like it!
