### ISSUE TITLE
Named function expressions

### ISSUE THREAD

**Issue by katspaugh** [daniellmb/JavaScript-Scope-Context-Coloring#3]
The project is super cool!

Just a minor issue:
Unlike named functions, the name in a named function expression must be visible only inside the function itself. The highlighter gets it right in the function body.

Also, note the incorrect highlighting of one of the closing parentheses.

![Screen Shot 2013-04-08 at 12 47 32 AM](https://f.cloud.github.com/assets/381895/349457/c872dede-9fc4-11e2-9457-7fe9f78511fc.png)

**Comment by daniellmb** [comment]
Fixed :)
