### ISSUE TITLE
Missing hoisting of variables?

### ISSUE THREAD

**Issue by JonAbrams** [daniellmb/JavaScript-Scope-Context-Coloring#4]
First of all, this project is absolutely brilliant, great job!

The issue:
If I have code in a function that references a variable from the parent scope that's declared after the function, it doesn't get coloured correctly.

For example (the variable late belongs to the 'white' scope not the 'green' scope):
![Screen Shot 2013-04-07 at 2 14 04 PM](https://f.cloud.github.com/assets/1243092/349485/2c42c32c-9fc8-11e2-81a8-f58cb61033a0.png)

**Comment by daniellmb** [comment]
Closing this issue, as using variables before they are defined is in general an anti-pattern.

**Comment by michaelficarra** [comment]
That's not a good reason to close this. This could lead to deceptive highlighting, where an accidentally shadowed reference is highlighted as if it wasn't.

**Comment by daniellmb** [comment]
Hmmm I see your point, I wonder if you could use the lint warning information to correct the coloring.

**Comment by michaelficarra** [comment]
Just do real scope analysis instead of this naive scanner approach. See [Constellation/escope](https://github.com/Constellation/escope).

**Comment by JonAbrams** [comment]
I'll try a better example. Is this an anti-pattern?

![Screen Shot 2013-04-13 at 10 15 43 AM](https://f.cloud.github.com/assets/1243092/376855/dc27f804-a45d-11e2-94f3-210c355bb525.png)

Example taken from: http://stackoverflow.com/questions/8597501/which-design-patterns-take-advantage-of-javascripts-hoisting-behavior
