### ISSUE TITLE
Should handle gaps in level lines

### ISSUE THREAD

**Issue by daniellmb** [daniellmb/JavaScript-Scope-Context-Coloring#6]
![Screen Shot 2013-04-09 at 12 57 17 PM](https://f.cloud.github.com/assets/108018/363658/6eb78056-a209-11e2-91d0-a4949c931eca.png)

**Comment by nadinengland** [comment]
I believe this is caused due to the JSLint colour info doesn't include comments. A fix for this might to adjust the `from` and `thru`'s from JSLint with an ongoing comment length counter.

**Comment by daniellmb** [comment]
You're right about it not including comments. Needed to skip the whole source code line (`from` `thru` is for scope change within a line)

**Comment by nadinengland** [comment]
:+1: that makes sense.
